import type { Metadata } from "next";
import Header from "@/components/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body>
        <Header />
=======
      <body className="dark">
>>>>>>> 7acd854cef9c4fd08a4e6f7ec42f1b42a9a6d4f2
        {children}
      </body>
    </html>
  );
}
